services:
  # South Delhi Realty Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: southdelhirealty-app
    restart: unless-stopped
    ports:
      - "7822:7822"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    # Use host networking to connect to external services
    network_mode: host
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7822/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.8'
        reservations:
          memory: 512M
          cpus: '0.4'
